jeffedwards/robyn_python

python/README.md, python/helpers/functions_data.py
=> Just added some general stuff

python/throw.py
=> showing how to add a file

source/fb_robyn.exec.R, source/fb_robyn.func.R, source/robyn playground.R
fb_robyn.exec.R and fb_robyn.func.R were copied from live version of Robyn
Checklist:
=> Robyn playground script added.

python/helpers/functions_data.py, python/robyn_playground_safe_for_r_updates.R, python/tests.py, source/fb_robyn.func.R
=> Updating R section to match that of the official branch

python/main.py
=> Code for reading input data file..

python/fb_robyn_func.py
=> first_commit

python/fb_robyn_func.py
=> Wshepherd get hyper names

python/fb_robyn_func.py
=> add transformation function

python/main.py
=> added dictionary to main execution

python/main.py
=> added default values for dictionary

python/main.py
=> added set_lift

python/fb_robyn_func.py, python/main.py
=> Input wrangling

python/fb_robyn_func.py
=> finished mm modeling and model collector

python/fb_robyn_func.py, python/main.py
=> added parameter check

python/fb_robyn_func.py, python/main.py
=> Jde refit 20210421

python/fb_robyn_func.py
=> debug transformation

python/fb_robyn_func.py
Added decomposition function
Might needs minor changes to be compatible with dependent functions
New feature
Checklist:
=> Davidchoe decomp function

python/fb_robyn_exec.py, python/fb_robyn_func.py, python/scratch_notes_delete_at_end.py
=> Jde core mmm

CONTRIBUTING.md, README.md, python/robyn_v02/robyn.py, source/fb_robyn.func.R
=> Small updates, plus merged master code from Robyn into branch

python/robyn_v02/example.py, python/robyn_v02/robyn.py
=> Tb and jd mmm function

python/robyn_v02/example.py, python/robyn_v02/robyn.py
=> added finished functions to the class

python/robyn_v02/example.py, python/robyn_v02/robyn.py
=> added additional comments

python/robyn_v02/robyn.py
=> made changes to the fit() function

python/robyn_v02/robyn.py
Reflecting WIP version of specific functions in robyn_mmm (ridge regression, set up environment, etc)
- New code
=> David func mmm (WIP)

python/robyn_v02/robyn.py
=> updated Robyn object

python/robyn_v02/robyn.py
=> updated robyn_engineering

python/robyn_v02/robyn.py
=> Reflect changes in 2.1 ver (David)

python/robyn_v02/robyn.py
=> adding calibratelift as calibrate_mmm to robyn.py

python/robyn_v02/robyn.py
=> updated calibrate_mmm function

python/robyn_v02/robyn.py
=> updated check conditions

python/robyn_v02/robyn.py
=> updated robyn engineering

python/robyn_v02/robyn.py
…Refit ridge regression
Checklist:
=> Update in mmm function 1) Setup env, 2) Fit ridge regression, 3) Refit
